package gomod_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/StevenACoffman/gowheels/internal/gomod"
)

func writeGoMod(t *testing.T, module string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"),
		[]byte("module "+module+"\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

func TestRepoURL(t *testing.T) {
	for _, tt := range []struct {
		module string
		want   string
	}{
		{"github.com/owner/repo", "https://github.com/owner/repo"},
		{"github.com/owner/repo/v2", "https://github.com/owner/repo"},
		{"github.com/owner/repo/v10", "https://github.com/owner/repo"},
		{"github.com/owner/repo/sub/pkg", "https://github.com/owner/repo"},
		{"gitlab.com/owner/repo", "https://gitlab.com/owner/repo"},
		{"codeberg.org/owner/repo", "https://codeberg.org/owner/repo"},
		{"example.com/owner/repo", ""},
		{"github.com/owner", ""},
		{"github.com/owner/repo // tool generated by goreleaser", "https://github.com/owner/repo"},
	} {
		t.Run(tt.module, func(t *testing.T) {
			dir := writeGoMod(t, tt.module)
			got := gomod.RepoURL(dir)
			if got != tt.want {
				t.Errorf("RepoURL(%q) = %q, want %q", tt.module, got, tt.want)
			}
		})
	}
}

func TestRepoURL_Missing(t *testing.T) {
	got := gomod.RepoURL(t.TempDir()) // no go.mod
	if got != "" {
		t.Errorf("got %q, want empty string", got)
	}
}
